Traceback (most recent call last):
  File "/Users/HondaDai/.pyenv/versions/2.7.9/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/Users/HondaDai/.pyenv/versions/2.7.9/lib/python2.7/site-packages/celery/__main__.py", line 30, in main
    main()
  File "/Users/HondaDai/.pyenv/versions/2.7.9/lib/python2.7/site-packages/celery/bin/celery.py", line 81, in main
    cmd.execute_from_commandline(argv)
  File "/Users/HondaDai/.pyenv/versions/2.7.9/lib/python2.7/site-packages/celery/bin/celery.py", line 769, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/Users/HondaDai/.pyenv/versions/2.7.9/lib/python2.7/site-packages/celery/bin/base.py", line 311, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/Users/HondaDai/.pyenv/versions/2.7.9/lib/python2.7/site-packages/celery/bin/celery.py", line 761, in handle_argv
    return self.execute(command, argv)
  File "/Users/HondaDai/.pyenv/versions/2.7.9/lib/python2.7/site-packages/celery/bin/celery.py", line 693, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/Users/HondaDai/.pyenv/versions/2.7.9/lib/python2.7/site-packages/celery/bin/worker.py", line 179, in run_from_argv
    return self(*args, **options)
  File "/Users/HondaDai/.pyenv/versions/2.7.9/lib/python2.7/site-packages/celery/bin/base.py", line 274, in __call__
    ret = self.run(*args, **kwargs)
  File "/Users/HondaDai/.pyenv/versions/2.7.9/lib/python2.7/site-packages/celery/bin/worker.py", line 212, in run
    state_db=self.node_format(state_db, hostname), **kwargs
  File "/Users/HondaDai/.pyenv/versions/2.7.9/lib/python2.7/site-packages/celery/worker/__init__.py", line 100, in __init__
    self.setup_instance(**self.prepare_args(**kwargs))
  File "/Users/HondaDai/.pyenv/versions/2.7.9/lib/python2.7/site-packages/celery/worker/__init__.py", line 136, in setup_instance
    self.on_init_blueprint()
  File "/Users/HondaDai/.pyenv/versions/2.7.9/lib/python2.7/site-packages/celery/apps/worker.py", line 143, in on_init_blueprint
    self._custom_logging = self.setup_logging()
  File "/Users/HondaDai/.pyenv/versions/2.7.9/lib/python2.7/site-packages/celery/apps/worker.py", line 184, in setup_logging
    redirect_stdouts=False, colorize=colorize, hostname=self.hostname,
  File "/Users/HondaDai/.pyenv/versions/2.7.9/lib/python2.7/site-packages/celery/app/log.py", line 70, in setup
    loglevel, logfile, colorize=colorize, hostname=hostname,
  File "/Users/HondaDai/.pyenv/versions/2.7.9/lib/python2.7/site-packages/celery/app/log.py", line 118, in setup_logging_subsystem
    root, logfile, loglevel, format, colorize, **kwargs
  File "/Users/HondaDai/.pyenv/versions/2.7.9/lib/python2.7/site-packages/celery/app/log.py", line 156, in _configure_logger
    colorize, **kwargs)
  File "/Users/HondaDai/.pyenv/versions/2.7.9/lib/python2.7/site-packages/celery/app/log.py", line 222, in setup_handlers
    handler = self._detect_handler(logfile)
  File "/Users/HondaDai/.pyenv/versions/2.7.9/lib/python2.7/site-packages/celery/app/log.py", line 233, in _detect_handler
    return WatchedFileHandler(logfile)
  File "/Users/HondaDai/.pyenv/versions/2.7.9/lib/python2.7/logging/handlers.py", line 391, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/Users/HondaDai/.pyenv/versions/2.7.9/lib/python2.7/logging/__init__.py", line 911, in __init__
    StreamHandler.__init__(self, self._open())
  File "/Users/HondaDai/.pyenv/versions/2.7.9/lib/python2.7/logging/__init__.py", line 936, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: '/Users/HondaDai/log/celery/celery.log'
Traceback (most recent call last):
  File "/Users/HondaDai/.pyenv/versions/2.7.9/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/Users/HondaDai/.pyenv/versions/2.7.9/lib/python2.7/site-packages/celery/__main__.py", line 30, in main
    main()
  File "/Users/HondaDai/.pyenv/versions/2.7.9/lib/python2.7/site-packages/celery/bin/celery.py", line 81, in main
    cmd.execute_from_commandline(argv)
  File "/Users/HondaDai/.pyenv/versions/2.7.9/lib/python2.7/site-packages/celery/bin/celery.py", line 769, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/Users/HondaDai/.pyenv/versions/2.7.9/lib/python2.7/site-packages/celery/bin/base.py", line 311, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/Users/HondaDai/.pyenv/versions/2.7.9/lib/python2.7/site-packages/celery/bin/celery.py", line 761, in handle_argv
    return self.execute(command, argv)
  File "/Users/HondaDai/.pyenv/versions/2.7.9/lib/python2.7/site-packages/celery/bin/celery.py", line 693, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/Users/HondaDai/.pyenv/versions/2.7.9/lib/python2.7/site-packages/celery/bin/worker.py", line 179, in run_from_argv
    return self(*args, **options)
  File "/Users/HondaDai/.pyenv/versions/2.7.9/lib/python2.7/site-packages/celery/bin/base.py", line 274, in __call__
    ret = self.run(*args, **kwargs)
  File "/Users/HondaDai/.pyenv/versions/2.7.9/lib/python2.7/site-packages/celery/bin/worker.py", line 212, in run
    state_db=self.node_format(state_db, hostname), **kwargs
  File "/Users/HondaDai/.pyenv/versions/2.7.9/lib/python2.7/site-packages/celery/worker/__init__.py", line 100, in __init__
    self.setup_instance(**self.prepare_args(**kwargs))
  File "/Users/HondaDai/.pyenv/versions/2.7.9/lib/python2.7/site-packages/celery/worker/__init__.py", line 136, in setup_instance
    self.on_init_blueprint()
  File "/Users/HondaDai/.pyenv/versions/2.7.9/lib/python2.7/site-packages/celery/apps/worker.py", line 143, in on_init_blueprint
    self._custom_logging = self.setup_logging()
  File "/Users/HondaDai/.pyenv/versions/2.7.9/lib/python2.7/site-packages/celery/apps/worker.py", line 184, in setup_logging
    redirect_stdouts=False, colorize=colorize, hostname=self.hostname,
  File "/Users/HondaDai/.pyenv/versions/2.7.9/lib/python2.7/site-packages/celery/app/log.py", line 70, in setup
    loglevel, logfile, colorize=colorize, hostname=hostname,
  File "/Users/HondaDai/.pyenv/versions/2.7.9/lib/python2.7/site-packages/celery/app/log.py", line 118, in setup_logging_subsystem
    root, logfile, loglevel, format, colorize, **kwargs
  File "/Users/HondaDai/.pyenv/versions/2.7.9/lib/python2.7/site-packages/celery/app/log.py", line 156, in _configure_logger
    colorize, **kwargs)
  File "/Users/HondaDai/.pyenv/versions/2.7.9/lib/python2.7/site-packages/celery/app/log.py", line 222, in setup_handlers
    handler = self._detect_handler(logfile)
  File "/Users/HondaDai/.pyenv/versions/2.7.9/lib/python2.7/site-packages/celery/app/log.py", line 233, in _detect_handler
    return WatchedFileHandler(logfile)
  File "/Users/HondaDai/.pyenv/versions/2.7.9/lib/python2.7/logging/handlers.py", line 391, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/Users/HondaDai/.pyenv/versions/2.7.9/lib/python2.7/logging/__init__.py", line 911, in __init__
    StreamHandler.__init__(self, self._open())
  File "/Users/HondaDai/.pyenv/versions/2.7.9/lib/python2.7/logging/__init__.py", line 936, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: '/Users/HondaDai/log/celery/celery.log'
